dependencies:
  - python=3
  -pip:
   -alabaster
   -anaconda-client
   -anaconda-navigator
   -alabaster                          
   -anaconda-client                    
   -anaconda-navigator                 
   -anaconda-project                   
   -anyio                              
   -appdirs                           
   -argh                               
   -argon2-cffi                        
   -asn1crypto                         
   -astroid                            
   -astropy                            
   -async-generator                    
   -atomicwrites                       
   -attrs                              
   -autopep8                          
   -Babel                              
   -backcall                           
   -backports.functools-lru-cache      
   -backports.shutil-get-terminal-size 
   -backports.tempfile                 
   -backports.weakref                  
   -bcrypt                             
   -beautifulsoup4                     
   -bitarray                           
   -bkcharts                           
   -black                              
   -bleach                             
   -bokeh                              
   -boto                               
   -Bottleneck                         
   -brotlipy                           
   -certifi                            
   -cffi                               
   -chardet                            
   -click                              
   -cloudpickle                        
   -clyent                             
   -colorama                           
   -comtypes                           
   -conda                              
   -conda-build                        
   -conda-content-trust                
   -conda-package-handling             
   -conda-repo-cli                     
   -conda-token                        
   -conda-verify                       
   -contextlib2                        
   -cryptography                       
   -cycler                             
   -Cython                             
   -cytoolz                            
   -dask                               
   -decorator                          
   -defusedxml                         
   -diff-match-patch                   
   -distributed                        
   -docutils                           
   -entrypoints                        
   -et-xmlfile                         
   -fastcache                          
   -filelock                           
   -flake8                             
   -Flask                              
   -fsspec                             
   -future                             
   -gevent                             
   -glob2                              
   -greenlet                           
   -h5py                              
   -HeapDict                           
   -html5lib                           
   -idna                               
   -imagecodecs                        
   -imageio                            
   -imagesize                          
   -importlib-metadata                 
   -iniconfig                          
   -intervaltree                       
   -ipykernel                          
   -ipython                            
   -ipython-genutils                   
   -ipywidgets                         
   -isort                              
   -itsdangerous                       
   -jdcal                              
   -jedi                               
   -Jinja2                             
   -joblib                             
   -json5                              
   -jsonschema                         
   -jupyter                            
   -jupyter-client                     
   -jupyter-console                    
   -jupyter-core                       
   -jupyter-packaging                  
   -jupyter-server                     
   -jupyterlab                         
   -jupyterlab-pygments                
   -jupyterlab-server                  
   -jupyterlab-widgets                 
   -keyring                            
   -kiwisolver                         
   -lazy-object-proxy                  
   -libarchive-c                       
   -llvmlite                           
   -locket                             
   -lxml                               
   -MarkupSafe                         
   -matplotlib                         
   -mccabe                             
   -menuinst                           
   -mistune                            
   -mkl-fft                            
   -mkl-random                         
   -mkl-service                        
   -mock                               
   -more-itertools                     
   -mpmath                             
   -msgpack                            
   -multipledispatch                   
   -mypy-extensions                    
   -navigator-updater                  
   -nbclassic                          
   -nbclient                           
   -nbconvert                          
   -nbformat                           
   -nest-asyncio                       
   -networkx                           
   -nltk                               
   -nose                               
   -notebook                           
   -numba                              
   -numexpr                            
   -numpy                              
   -numpydoc                           
   -olefile                            
   -opencv-contrib-python              
   -opencv-python                      
   -openpyxl                           3.0.7
   -packaging                          20.9
   -pandas                             1.2.4
   -pandocfilters                      1.4.3
   -paramiko                           2.7.2
   -parso                              0.7.0
   -partd                              1.2.0
   -path                               15.1.2
   -pathlib2                           2.3.5
   -pathspec                           0.7.0
   -patsy                              0.5.1
   -pep8                               1.7.1
   -pexpect                            4.8.0
   -pickleshare                        0.7.5
   -Pillow                             8.2.0
   -pip                                21.0.1
   -pkginfo                            1.7.0
   -pluggy                             0.13.1
   -ply                                3.11
   -prometheus-client                  0.10.1
   -prompt-toolkit                     3.0.17
   -psutil                             5.8.0
   -ptyprocess                         0.7.0
   -py                                 1.10.0
   -pycodestyle                        2.6.0
   -pycosat                            0.6.3
   -pycparser                          2.20
   -pycurl                             7.43.0.6
   -pydocstyle                         6.0.0
   -pyerfa                             1.7.3
   -pyflakes                           2.2.0
   -Pygments                           2.8.1
   -PyJWT                              2.1.0
   -pylint                             2.7.4
   -pyls-black                         0.4.6
   -pyls-spyder                        0.3.2
   -PyNaCl                             1.4.0
   -pyodbc                             4.0.0-unsupported
   -pyOpenSSL                          20.0.1
   -pyparsing                          2.4.7
   -pyreadline                         2.1
   -pyrsistent                         0.17.3
   -PySocks                            1.7.1
   -pytest                             6.2.3
   -python-dateutil                    2.8.1
   -python-jsonrpc-server              0.4.0
   -python-language-server             0.36.2
   -pytz                               2021.1
   -PyWavelets                         1.1.1
   -pywin32                            227
   -pywin32-ctypes                     0.2.0
   -pywinpty                           0.5.7
   -PyYAML                             5.4.1
   -pyzmq                              20.0.0
   -QDarkStyle                         2.8.1
   -QtAwesome                          1.0.2
   -qtconsole                          5.0.3
   -QtPy                               1.9.0
   -regex                              2021.4.4
   -requests                           2.25.1
   -rope                               0.18.0
   -Rtree                              0.9.7
   -ruamel-yaml-conda                  0.15.100
   -scikit-image                       0.18.1
   -scikit-learn                       0.24.1
   -scipy                              1.6.2
   -seaborn                            0.11.1
   -Send2Trash                         1.5.0
   -setuptools                         52.0.0.post20210125
   -simplegeneric                      0.8.1
   -singledispatch                     0.0.0
   -sip                                4.19.13
   -six                                1.15.0
   -sniffio                            1.2.0
   -snowballstemmer                    2.1.0
   -sortedcollections                  2.1.0
   -sortedcontainers                   2.3.0
   -soupsieve                          2.2.1
   -Sphinx                             4.0.1
   -sphinxcontrib-applehelp            1.0.2
   -sphinxcontrib-devhelp              1.0.2
   -sphinxcontrib-htmlhelp             1.0.3
   -sphinxcontrib-jsmath               1.0.1
   -sphinxcontrib-qthelp               1.0.3
   -sphinxcontrib-serializinghtml      1.1.4
   -sphinxcontrib-websupport           1.2.4
   -spyder                             4.2.5
   -spyder-kernels                     1.10.2
   -SQLAlchemy                         1.4.7
   -statsmodels                        0.12.2
   -sympy                              1.8
   -tables                             3.6.1
   -tblib                              1.7.0
   -terminado                          0.9.4
   -testpath                           0.4.4
   -textdistance                       4.2.1
   -threadpoolctl                      2.1.0
   -three-merge                        0.1.1
   -tifffile                           2021.4.8
   -toml                               0.10.2
   -toolz                              0.11.1
   -tornado                            6.1
   -tqdm                               4.59.0
   -traitlets                          5.0.5
   -typed-ast                          1.4.2
   -typing-extensions                  3.7.4.3
   -ujson                              4.0.2
   -unicodecsv                         0.14.1
   -urllib3                            1.26.4
   -watchdog                           1.0.2
   -wcwidth                            0.2.5
   -webencodings                       0.5.1
   -Werkzeug                           1.0.1
   -wheel                              0.36.2
   -widgetsnbextension                 3.5.1
   -win-inet-pton                      1.1.0
   -win-unicode-console                0.5
   -wincertstore                       0.2
   -wrapt                              1.12.1
   -xlrd                               2.0.1
   -XlsxWriter                         1.3.8
   -xlwings                            0.23.0
   -xlwt                               1.3.0
   -xmltodict                          0.12.0
   -yapf                               0.31.0
   -zict                               2.0.0
   -zipp                               3.4.1
   -zope.event                         4.5.0
   -zope.interface                     5.3.0
